version: 2

models:
  - name: fact_order_items
    description: "Mart order items"
    columns:
      - name: order_id
        tags: ['test_mart']
        tests:
          - not_null
      - name: date_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: customer_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: product_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: seller_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: dim_customer
    columns:
      - name: customer_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: region_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: dim_product
    columns:
      - name: product_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: dim_seller
    columns:
      - name: seller_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: history_customer
    columns:
      - name: customer_valid_key
        tags: ['test_mart']
        tests:
          - unique
  - name: history_seller
    columns:
      - name: seller_valid_key
        tags: ['test_mart']
        tests:
          - unique
  - name: history_product
    columns:
      - name: product_valid_key
        tags: ['test_mart']
        tests:
          - unique
  - name: fact_order_payment
    columns:
      - name: order_payment_key
        tags: ['test_mart']
        tests:
          - unique
          - not_null
  