version: 2

models:
  - name: fact_order_items
    description: "Mart order items"
    columns:
      - name: order_id
        tags: ['test_mart']
        tests:
          - not_null
      - name: date_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: customer_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: product_key
        tags: ['test_mart']
        tests:
          - not_null
      - name: seller_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: dim_order 
    columns:
      - name: order_key 
        tags: ['test_mart']
        tests:
          - not_null
          - unique
  - name: dim_customer
    columns:
      - name: customer_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: dim_product
    columns:
      - name: product_key
        tags: ['test_mart']
        tests:
          - not_null
  - name: dim_seller
    columns:
      - name: seller_key
        tags: ['test_mart']
        tests:
          - not_null
  